# 넘파이 기초

In [6]:
import numpy as np

a = np.array(1)
a




array(1)

### 배열 생성

In [10]:
ndarr_1 = np.array([1,2,3])
print(ndarr_1)  # 콤마 없이 띄어쓰기로 나타남

[1 2 3]


In [7]:
ndarr_2=np.array([1,2.0,3])
print(ndarr_2)  #플롯 형식으로 출력 .0생략

[1. 2. 3.]


In [9]:
ndarr_3 = np.array([1,2.0,'3'])
print(ndarr_3) # 문자열로 출력

['1' '2.0' '3']


### 배열의 정보 확인
>  자료형 확인 속성    ndarray.dtype

In [12]:
print(ndarr_1.dtype)
print(ndarr_2.dtype)
print(ndarr_3.dtype)

int32
float64
<U32


In [14]:
print(np.array(1+2j).dtype)  #복소수 출력
print(np.array(print).dtype)

complex128
object


### 자료형 지정
> dtype 속성을 사용해 자료형 지정

In [15]:
dtype1 = np.array([1,2,3], dtype=np.int8)
print(dtype1.dtype)

int8


In [18]:
dtype2 = np.array([1,2,3], dtype=np.float)
print(dtype2.dtype)

float64


C:\Users\admin\AppData\Local\Temp\ipykernel_10612\2523159928.py:1: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  dtype2 = np.array([1,2,3], dtype=np.float)


In [19]:
dtype3 = np.array([1,2,3], dtype=np.str)
print(dtype3.dtype)

<U1


C:\Users\admin\AppData\Local\Temp\ipykernel_10612\216843007.py:1: DeprecationWarning: `np.str` is a deprecated alias for the builtin `str`. To silence this warning, use `str` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.str_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  dtype3 = np.array([1,2,3], dtype=np.str)


In [21]:
dtype4 = np.array([1,2.0,'3'], dtype=np.int)
print(dtype4)
print(dtype4.dtype)

[1 2 3]
int32


C:\Users\admin\AppData\Local\Temp\ipykernel_10612\542048979.py:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  dtype4 = np.array([1,2.0,'3'], dtype=np.int)


In [22]:
dtype5 = np.array([1,'data',print], dtype=np.float)
print(dtype5.dtype)   #ValueError

C:\Users\admin\AppData\Local\Temp\ipykernel_10612\838612793.py:1: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  dtype5 = np.array([1,'data',print], dtype=np.float)


ValueError: could not convert string to float: 'data'

### 배열의 정보 확인
> 배열 크기 확인

In [23]:
print(ndarr_1.shape)

(3,)


> 배열 차원 확인

In [24]:
print(ndarr_1.ndim)

1


### 배열 생성
> 1차원 배열 생성

In [28]:
vector = np.array([1,2,3])
print(vector)
print(vector.shape)
print(vector.ndim)
print(vector.dtype)

[1 2 3]
(3,)
1
int32


> 2차원 배열 생성

In [31]:
matrix = np.array([[1,2,3],[4,5,6]])
print(matrix)
print(matrix.shape)
print(matrix.ndim)
print(matrix.dtype)

[[1 2 3]
 [4 5 6]]
(2, 3)
2
int32


> 3차원 배열 생성

In [32]:
tensor = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(tensor)
print(tensor.shape)
print(tensor.ndim)
print(tensor.dtype)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
(2, 2, 3)
3
int32


### 배열의 정보 확인
. 배열 요소의 개수 확인

In [34]:
print(vector.size)
print(matrix.size)
print(tensor.size)

3
6
12


In [37]:
# 배열 생성 예제
tensor = np.array([[1,2,3],[2,4,6],[3,6,9]])
print(tensor)
print(tensor.shape)   # 모형
print(tensor.ndim)    # 차원
print(tensor.size)   # 크기

[[1 2 3]
 [2 4 6]
 [3 6 9]]
(3, 3)
2
9


### 자료형 변환(리스트)
> 리스트 <-> ndarray 변환

In [39]:
# list -> ndarray
list1 = [1,2,3]
arr1 = np.array(list1)
print(arr1)

[1 2 3]


In [42]:
#ndarray -> list
arr2 = np.array([1,2,3])
list2 = list(arr2)
print(list2)

[1, 2, 3]


In [44]:
# 2차원 리스트 변환
list3 = [[1,2,3],[4,5,6]]
arr3 = np.array(list3)
print(arr3)

[[1 2 3]
 [4 5 6]]


In [47]:
# shape 이 다른 리스트인 경우
list4 = [[1,2,3,4],[5,6,7]]
arr4 = np.array(list4)
print(arr4)
print(arr4.size, arr4.shape, arr4.ndim)

[list([1, 2, 3, 4]) list([5, 6, 7])]
2 (2,) 1


C:\Users\admin\AppData\Local\Temp\ipykernel_10612\595011856.py:3: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  arr4 = np.array(list4)


### 자료형 변환(튜플) - 리스트와 동일

In [48]:
# tuple -> ndarray
tuple1 = (1,2,3)
arr= np.array(tuple1)
print(arr)

[1 2 3]


In [49]:
# ndarray -> tuple
arr2 = np.array([1,2,3])
tuple2 = tuple(arr2)
print(tuple2)

(1, 2, 3)


### 자료형 변환(세트, 딕셔너리)

In [50]:
# 세트 변환
set1 = {1,2,3}
arr = np.array(set1)
print(arr)

{1, 2, 3}


In [51]:
# 딕셔너리 변환
dict1 = {'a':1,'b':2,'c':3}
arr= np.array(dict1)
print(arr)

{'a': 1, 'b': 2, 'c': 3}


### 배열 인덱싱

In [60]:
# 리스트 인덱싱과 유사
list_ = [[[1,2],[3,4]],[[5,6],[7,8]]]
print(list_[0][0][0])
print(list_[0][1][1])
print(list_[1][1][0])

1
4
7


In [62]:
# 리스트 인덱싱과 유사
arr_ = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(arr_[0][0][0])
print(arr_[0][1][1])
print(arr_[1][1][0])

1
4
7


In [63]:
arr_ = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(arr_[0,0,0])
print(arr_[0,1,1])
print(arr_[1,1,0])

1
4
7


In [69]:
# ndarray의 인덱싱
arr_1 = np.array([[1,2],
                  [3,4],
                  [5,6]])
# 0행 가져와서 2차원 배열 만들기
print(arr_1[[0]])

# 0, 2행 가져와서 2차원 배열 만들기
print(arr_1[[0,2]])

# 0,1,2번째 행에서 0,1,0 번째 값 가져오기
print(arr_1[[0,1,2],[0,1,0]])

# 0번째 행에서 인덱스1 번째 값 가져오기
print(arr_1[[0,0],[1,1]])

[[1 2]]
[[1 2]
 [5 6]]
[1 4 5]
[2 2]


In [71]:
arr_2 = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
b = np.array([0,1,2,3])
c = np.array([0,2,0,1])
print(arr_2[b,c])

[ 1  6  7 11]


In [73]:
# Boolean 인덱싱
arr = np.array([1,2,3,4,5])
print(arr[[True, False, True, True, False]])

[1 3 4]


In [74]:
arr = np.array([1,2,3,4,5])
arr[arr % 3 ==0]

array([3])

In [80]:
# 문제
score = np.array([[78,91,84,89,93,65],[82,87,96,79,91,73]])
print(score[0][score[0] >= 90])
print(score[1][score[1] >= 90])

[91 93]
[96 91]


### 배열 슬라이싱
> ndarray의 슬라이싱
- 행과 열 부분을 나눠서 슬라이싱 가능
- 다차원 배열의 부분 데이터를 추출할 때 유용

In [9]:
import numpy as np

In [10]:
matrix = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20]])

# 0열 전체 슬라이싱
print(matrix[:,0])    #([row:column])

# 0열 전체 슬라이싱(2차원 유지)
print(matrix[:,:1])    # print(matrix[:,[0]])

[ 1  6 11 16]
[[ 1]
 [ 6]
 [11]
 [16]]


In [13]:
# 1행 전체 슬라이싱
print(matrix[1,:])
print(matrix[1])

# 1행 전체 슬라이싱(2차원 유지)
print(matrix[1:2,:])    # print(matrix[[1]])

[ 6  7  8  9 10]
[ 6  7  8  9 10]
[[ 6  7  8  9 10]]


In [22]:
# 3~4열 전체 슬라이싱
print(matrix[:,3:])

# 0행, 1~3열 슬라이싱
print(matrix[0,1:-1])   # print(matrix[0,1:4])b

[[ 4  5]
 [ 9 10]
 [14 15]
 [19 20]]
[2 3 4]


In [25]:
# 2~3행, 2~4열 슬라이싱
print(matrix[-2:,-3:])

# 1~2행, 1~2열 슬라이싱
print(matrix[1:-1,1:3])

[[13 14 15]
 [18 19 20]]
[[ 7  8]
 [12 13]]


### 배열 인덱싱, 슬라이싱 복합

In [27]:
# 1,3행, 2~4열 슬라이싱
print(matrix[[1,3],2:])

# 1~2행, 1,3열 슬라이싱
print(matrix[1:-1,[1,3]])

[[ 8  9 10]
 [18 19 20]]
[[ 7  9]
 [12 14]]


In [71]:
# 문제3
tensor = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(tensor)

print(tensor[[1,0,0],[1,0,1],[0,1,2]])   #[각자 위치한 랭크 위치],[행위치],[열위치]


[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
[10  2  6]


In [72]:
# 문제4
print(tensor[0,0:,0:2])

print(tensor[1,:,2])

[[1 2]
 [4 5]]
[ 9 12]
