# 넘파이 활용

### Reshape

In [2]:
import numpy as np

In [25]:
# array.rehape(size)
arr = np.array([[1,2,3],[4,5,6]])  # 2x3 행렬
print(arr.reshape(3,2))            # 3x2 행렬로 변환

[[1 2]
 [3 4]
 [5 6]]


In [5]:
print(arr.reshape(6,1))
print(arr.reshape(1,6))

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
[[1 2 3 4 5 6]]


In [12]:
print(arr.reshape(3,1,2))

[[[1 2]]

 [[3 4]]

 [[5 6]]]


In [9]:
print(arr.reshape(6))

[1 2 3 4 5 6]


In [13]:
print(arr.reshape(-1,2))

[[1 2]
 [3 4]
 [5 6]]


In [14]:
print(arr.reshape(2,-1))

[[1 2 3]
 [4 5 6]]


In [17]:
tensor = np.array(range(1,37))
print(tensor)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36]


In [23]:
print(tensor.reshape(3,3,4))

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]

 [[25 26 27 28]
  [29 30 31 32]
  [33 34 35 36]]]


In [22]:
# 문제 - tensor 배열을 2차원 배열로 변형(열의 개수는 9)
print(tensor.reshape(-1,9))

[[ 1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18]
 [19 20 21 22 23 24 25 26 27]
 [28 29 30 31 32 33 34 35 36]]


### Flatten
> 다차원 배열을 1차원 배열로 변형

In [30]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr.flatten())

[1 2 3 4 5 6]


In [31]:
print(tensor.flatten())

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36]


### Arange
- range 함수와 비슷한 기능
- 갑의 범위를 지정하여 값이 채워져 있는 배열을 생성
- 특정한 규칙에 따라 증가하는 값을 넣는 것도 가능

In [32]:
print(np.arange(30))   # np.array(range(30))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]


In [38]:
# 간격지정 (start,end,step)
print(np.arange(0,10,2))

print(np.arange(1,2,0.2))

print(np.arange(10,0,-1))

[0 2 4 6 8]
[1.  1.2 1.4 1.6 1.8]
[10  9  8  7  6  5  4  3  2  1]


In [39]:
# arange_reshape
np.arange(1,26).reshape(5,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [41]:
print(np.arange(0,6,0.2).reshape(3,2,5))

[[[0.  0.2 0.4 0.6 0.8]
  [1.  1.2 1.4 1.6 1.8]]

 [[2.  2.2 2.4 2.6 2.8]
  [3.  3.2 3.4 3.6 3.8]]

 [[4.  4.2 4.4 4.6 4.8]
  [5.  5.2 5.4 5.6 5.8]]]


In [53]:
# 문제3
print(np.arange(100,191,10).reshape(2,5))

[[100 110 120 130 140]
 [150 160 170 180 190]]


In [58]:
# 문제4 (3차원배열로)
print(np.arange(-2,2.1,0.5).reshape(1,3,3))  # reshape(3,1,3) or (1,3,3) 0r (3,3,1)

[[[-2.  -1.5 -1. ]
  [-0.5  0.   0.5]
  [ 1.   1.5  2. ]]]


### Zeros
- 0으로 채워진 배열 생성

In [59]:
print(np.zeros(shape=(5,), dtype=np.int8))

[0 0 0 0 0]


In [64]:
print(np.zeros((5),int))

[0 0 0 0 0]


In [65]:
print(np.zeros((2,3)))  # dtype = float64

[[0. 0. 0.]
 [0. 0. 0.]]


### Ones
- 1으로 채워진 배열 생성

In [66]:
print(np.ones(shape=(5,), dtype=np.int8))

[1 1 1 1 1]


In [67]:
print(np.ones((5),int))

[1 1 1 1 1]


In [68]:
print(np.ones((2,3))) 

[[1. 1. 1.]
 [1. 1. 1.]]


### Empty
- shape만 주어지고 비어있는 배열 생성
- 배열을 생성만 하고 값을 주지 않아 메모리에 저장되어 있던 기준

In [70]:
print(np.empty(shape=(10,), dtype = np.int32))

[0 0 0 0 0 0 0 0 0 0]


In [71]:
print(np.empty((2,5),np.int8))

[[  64  -98  -25 -101   -8]
 [   1    0    0    0    0]]


### Zeros_like / Ones_like / Empty_like
- 입력받은 배열과 같은 shape, dtype의 배열 생성

In [72]:
matrix = np.arange(24).reshape(4,6)
print(np.zeros_like(matrix))

[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]


In [73]:
matrix = np.arange(-2,2,0.2).reshape(2,10)
print(np.ones_like(matrix))

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [75]:
matrix = np.arange(30).reshape(5,6)
print(np.empty_like(matrix))

[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]


### Identity
- 단위 행렬-주대각선의 값이 1이고 나머지는 0인 정사각 행렬

In [77]:
print(np.identity(5,dtype=np.int8))

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


In [78]:
print(np.identity(5,dtype=np.str_))

[['1' '' '' '' '']
 ['' '1' '' '' '']
 ['' '' '1' '' '']
 ['' '' '' '1' '']
 ['' '' '' '' '1']]


### Eye
- 대각선이 1로 채워지는 행렬
- 대각선의 시작 위치 지정 가능

In [79]:
print(np.eye(5,dtype=np.int8))

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


In [80]:
print(np.eye(5, M=10, k=-1))

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]]


### Full
- 입력값으로 채워지는 행렬

In [81]:
print(np.full((2,5),3))

[[3 3 3 3 3]
 [3 3 3 3 3]]


In [82]:
print(np.full((5,4),'a'))

[['a' 'a' 'a' 'a']
 ['a' 'a' 'a' 'a']
 ['a' 'a' 'a' 'a']
 ['a' 'a' 'a' 'a']
 ['a' 'a' 'a' 'a']]


In [85]:
np.ones((3,3)) * 3

array([[3., 3., 3.],
       [3., 3., 3.],
       [3., 3., 3.]])

### Random.randint
- 주어진 범위 안의 랜덤한 값을 뽑는 함수

In [88]:
# 0~5 정수 중 랜덤
print(np.random.randint(6))

1


In [87]:
print(np.random.randint(1,20))

3


In [89]:
import random

In [91]:
random.randint(1,10)

6

In [90]:
np.random.randint(1,20,2)

array([ 8, 14])

### Random.rand
- 랜덤한 값으로 채워지는 배열

In [93]:
# 0~1 사이의 값 가짐
print(np.random.rand(3))

[0.44035503 0.22464728 0.31352227]


In [94]:
print(np.random.rand(3,2))

[[0.16381496 0.52416142]
 [0.32518644 0.63274718]
 [0.04878885 0.47374999]]


In [95]:
np.random.rand(2,5)

array([[0.23233808, 0.98117963, 0.21063887, 0.21315365, 0.37056449],
       [0.00689103, 0.097329  , 0.00616252, 0.50394554, 0.77959851]])

### Random.randn
-랜덤한 값으로 채워지는 배열
- 평균0, 표준편차 1의 가우시안 표준정규분포 난수를 shape형태의 배열로 생성

In [96]:
print(np.random.randn(3))

[-2.63325022  0.88317554  0.9162906 ]


In [97]:
print(np.random.randn(3,2))

[[ 0.80132121  2.19142676]
 [-0.80154598  2.64298262]
 [ 0.04944934 -0.47620701]]


## 연산함수
- 배열의 요소값들을 이용하여 연산을 할 수 있게 해주는 함수

### 합(sum)

In [102]:
matrix = np.arange(1,7).reshape(2,3)
print(matrix)

[[1 2 3]
 [4 5 6]]


In [103]:
print(matrix.sum())

21


In [104]:
print(matrix.sum(axis=0)) # 행끼리 더하기(위아래)
print(matrix.sum(axis=1)) # 열끼리 더하기(좌우)

[5 7 9]
[ 6 15]


In [106]:
# 3차원 배열의 합
tensor = np.arange(1,19).reshape(3,2,3)
print(tensor)
print(tensor.sum())

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]
171


In [111]:
print(tensor.sum(axis=0))
print(tensor.sum(axis=1))
print(tensor.sum(axis=2))

[[21 24 27]
 [30 33 36]]
[[ 5  7  9]
 [17 19 21]
 [29 31 33]]
[[ 6 15]
 [24 33]
 [42 51]]


### 평균(mean)

In [114]:
print(tensor.mean())  # 전체 평균
print(tensor.mean(axis=0))
print(tensor.mean(axis=1))
print(tensor.mean(axis=2))

9.5
[[ 7.  8.  9.]
 [10. 11. 12.]]
[[ 2.5  3.5  4.5]
 [ 8.5  9.5 10.5]
 [14.5 15.5 16.5]]
[[ 2.  5.]
 [ 8. 11.]
 [14. 17.]]


### 표준편차(std)

In [118]:
print(matrix.std())
print(matrix.std(axis=0))  # 행끼리
print(matrix.std(axis=1))  # 열끼리

1.707825127659933
[1.5 1.5 1.5]
[0.81649658 0.81649658]


### 그 외 수학 연산자
- 지수. 로그

In [119]:
# 지수(exp)
print(np.exp(matrix))

[[  2.71828183   7.3890561   20.08553692]
 [ 54.59815003 148.4131591  403.42879349]]


In [120]:
# 로그(log)
print(np.log(matrix))


[[0.         0.69314718 1.09861229]
 [1.38629436 1.60943791 1.79175947]]


In [121]:
# 제곱근(sqrt)
print(np.sqrt(matrix))

[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]]


In [124]:
# 삼각함수(sin)
print(np.sin(matrix))

# cos
print(np.cos(matrix))

# tan
print(np.tan(matrix))

[[ 0.84147098  0.90929743  0.14112001]
 [-0.7568025  -0.95892427 -0.2794155 ]]
[[ 0.54030231 -0.41614684 -0.9899925 ]
 [-0.65364362  0.28366219  0.96017029]]
[[ 1.55740772 -2.18503986 -0.14254654]
 [ 1.15782128 -3.38051501 -0.29100619]]


### 배열 정렬(Sort)

In [129]:
# 1차원 배열 정렬
vector = np.array([np.random.randint(1,100)
                  for n in range(5)])      # 리스트에 담기. for 문 조건에 만족하는 값을 넣음.
print(vector)

print(np.sort(vector))
print(np.sort(vector)[::-1])

[82 37 82 34 77]
[34 37 77 82 82]
[82 82 77 37 34]


In [131]:
x = 3
[x for i in range(5)]

[3, 3, 3, 3, 3]

In [133]:
list_ = [1,2,3,4,5,6,7,8,9,10]
list2_ = [num * 3 for num in list_ if num % 2 == 1]  #나머지가1이 남는 애들을 넣음. 넣어서 3을 곱함.
print(list2_)

[3, 9, 15, 21, 27]


In [134]:
matrix = np.array([np.random.randint(1,100)
                  for n in range(20)]).reshape(4,5)
print(matrix)

[[89 70 38 88 45]
 [19 43 50 51 50]
 [50 60 55 92 71]
 [15 91 68 27 31]]


In [137]:
print(np.sort(matrix))  # 열기준 정렬됨
print(np.sort(matrix)[::-1]) # 전체 오름차순
print(np.sort(matrix,axis=0)) # 행기준 정렬

[[38 45 70 88 89]
 [19 43 50 50 51]
 [50 55 60 71 92]
 [15 27 31 68 91]]
[[15 27 31 68 91]
 [50 55 60 71 92]
 [19 43 50 50 51]
 [38 45 70 88 89]]
[[15 43 38 27 31]
 [19 60 50 51 45]
 [50 70 55 88 50]
 [89 91 68 92 71]]


### 배열 합치기(Vstack)

In [140]:
vector1 = np.array([1,2,3])
vector2 = np.array([4,5,6])
print(np.vstack([vector1,vector2]))

[[1 2 3]
 [4 5 6]]


In [141]:
vector1 = np.array([1,2,3]).reshape(3,1)
vector2 = np.array([4,5,6]).reshape(3,1)
print(np.vstack([vector1,vector2]))

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


### 배열합치기(Concatenate)

In [144]:
vector1 = np.array([1,2,3])
vector2 = np.array([4,5,6])
print(np.concatenate([vector1,vector2],axis=0))   # axit=1 은 에러

[1 2 3 4 5 6]


In [145]:
vector1 = np.array([1,2,3]).reshape(3,1)
vector2 = np.array([4,5,6]).reshape(3,1)
print(np.concatenate([vector1,vector2],axis=1))

[[1 4]
 [2 5]
 [3 6]]


In [4]:
matrix1 = np.array([[1,2,3],[1,2,3]]).reshape(3,2)
vector2 = np.array([4,5,6]).reshape(3,1)
print(np.concatenate([matrix1,vector2],axis=1))

[[1 2 4]
 [3 1 5]
 [2 3 6]]


In [146]:
matrix1 = np.arange(1,5).reshape(2,2)
matrix2 = np.arange(5,9).reshape(2,2)
print(np.concatenate([matrix1,matrix2],axis=0))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [148]:
matrix1 = np.arange(1,5).reshape(2,2)
matrix2 = np.arange(5,9).reshape(2,2)
print(np.concatenate([matrix1,matrix2],axis=1))


[[1 2 5 6]
 [3 4 7 8]]


### 행 / 열 바꾸기(transpose)

In [150]:
matrix3 = np.array([[5,6]])
print(matrix3)

[[5 6]]


In [152]:
print(matrix3.transpose())
print(matrix3.T)

[[5]
 [6]]
[[5]
 [6]]


In [154]:
print(np.concatenate([matrix1,matrix2]))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [170]:
print(np.concatenate([matrix1, matrix3.T], axis=1))

[[1 2 5]
 [3 4 6]]


 ### 인덱스 반환 함수
 - 최대값, 최소값의 인덱스 argmax, argnim

In [3]:
a = np.arange(1,11).reshape(2,5)
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [6]:
print(np.argmax(1), np.argmin(1))

0 0


In [163]:
print(np.argmax(a,axis=0))

[1 1 1 1 1]


In [164]:
b = np.array([[1,2,3,4],[2,3,4,1],[3,4,1,2]])
print(b)

[[1 2 3 4]
 [2 3 4 1]
 [3 4 1 2]]


In [169]:
print(np.argmax(b,axis=1))
print(np.argmax(b,axis=0))

[3 2 1]
[2 2 1 0]


### 배열 인덱싱(Fancy Index)
- 인덱스 값을 가지는 배열을 통해 인덱싱

In [177]:
a = np.arange(1,11)
b = np.array([3,4,5,6])
print(a)
print(b)

print(a[b])

[ 1  2  3  4  5  6  7  8  9 10]
[3 4 5 6]
[4 5 6 7]


In [179]:
a = np.arange(10,20)
b = np.argmax(a)
print(a)
print(b)

print(a[b])

[10 11 12 13 14 15 16 17 18 19]
9
19
