# 산술연산

In [1]:
import numpy as np

In [3]:
# 리스트 덧셈
list1 = [1,2,3]
list2 = [4,5,6]
print(list1+list2)

[1, 2, 3, 4, 5, 6]


In [4]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
print(arr1+ arr2)

[5 7 9]


In [6]:
arr1= np.arange(1,7,dtype=np.float32).reshape(2,3)
arr2= np.arange(11,17,dtype=np.int32).reshape(2,3)
print(arr1+arr2)
print(arr2-arr1)

[[12. 14. 16.]
 [18. 20. 22.]]
[[10. 10. 10.]
 [10. 10. 10.]]


In [10]:
print(arr1*arr2)
print(arr2/arr1)
print(arr1**arr2)  #제곱

[[11. 24. 39.]
 [56. 75. 96.]]
[[11.          6.          4.33333333]
 [ 3.5         3.          2.66666667]]
[[1.00000000e+00 4.09600000e+03 1.59432300e+06]
 [2.68435456e+08 3.05175781e+10 2.82110991e+12]]


In [11]:
print(arr2//arr1) #몫
print(arr2 % arr1) #나머지

[[11.  6.  4.]
 [ 3.  3.  2.]]
[[0. 0. 1.]
 [2. 0. 4.]]


In [12]:
print(np.add(arr1,arr2))

[[12. 14. 16.]
 [18. 20. 22.]]


In [14]:
print(np.subtract(arr1,arr2))

[[-10. -10. -10.]
 [-10. -10. -10.]]


In [15]:
print(np.multiply(arr1,arr2))

[[11. 24. 39.]
 [56. 75. 96.]]


In [16]:
print(np.divide(arr2,arr1))

[[11.          6.          4.33333333]
 [ 3.5         3.          2.66666667]]


### Broadingcasting
- 연산하고자 하는 배열의 모양이 다른 경우의 연산

In [18]:
arr3 = np.arange(10).reshape(5,2)
arr4 = np.arange(10).reshape(2,5)
print(arr3+arr4)  # 불가능

ValueError: operands could not be broadcast together with shapes (5,2) (2,5) 

In [19]:
scalar = 10
vector = np.array([1,2,3])
print(scalar + vector)

[11 12 13]


In [20]:
scalar = 10
matrix = np.array([[1,2,3],[4,5,6]])
print(scalar + matrix)

[[11 12 13]
 [14 15 16]]


In [25]:
# 벡터와 매트릭스의 연산
matrix = np.arange(1,10).reshape(3,3)
vector = np.arange(11,14).reshape(1,3)
print(matrix+vector)

[[12 14 16]
 [15 17 19]
 [18 20 22]]


In [27]:
# 벡터와 벡터의 브로드캐스팅 연산
arr1 = np.array([1,2,3])
arr2 = np.array([1,2,3]).reshape(3,1)
print(arr1)
print(arr2)

[1 2 3]
[[1]
 [2]
 [3]]


In [28]:
np.broadcast(arr1,arr2)

In [29]:
arr3= np.array([1,2,3])
arr4 = np.array([4,5,6])
np.broadcast(arr3,arr4)

In [34]:
arr1 = np.array([1,2,3])
arr2 = np.array([1,2,3])
print(arr1*arr2)

# np.dot 사용
arr1 = np.array([1,2,3])
arr2 = np.array([1,2,3]).T
print(np.dot(arr1,arr2))

[1 4 9]
14


In [35]:
print(arr1@arr2)

14


In [36]:
arr3 = np.arange(1,7).reshape(2,3)
arr4 = np.arange(11,17).reshape(3,2)
print(np.dot(arr3,arr4))

[[ 82  88]
 [199 214]]
