# 파일 입출력

In [1]:
import numpy as np

### 파일 처리
- ndarray의 정보를 파일로 저장할 수 있다
- 일반적인 파일 확장자는 npy를 사용한다

In [5]:
n = np.random.randn(3,5)
print(n)
n.tofile('n.npy')

[[ 0.64964899  0.83399456  0.37257043  0.06854129 -0.36378131]
 [ 1.10935929  0.5612545  -0.02747347 -2.49208788  0.1992881 ]
 [-0.4970017  -1.17475738 -0.68522354 -2.32770089 -1.82765734]]


In [8]:
# 파일 불러오기
m = np.fromfile('n.npy')
print(m)

[ 0.64964899  0.83399456  0.37257043  0.06854129 -0.36378131  1.10935929
  0.5612545  -0.02747347 -2.49208788  0.1992881  -0.4970017  -1.17475738
 -0.68522354 -2.32770089 -1.82765734]


In [11]:
m2 = np.fromfile('C:/STUDY/StudyPython22/n.npy')
print(m2)

[ 0.64964899  0.83399456  0.37257043  0.06854129 -0.36378131  1.10935929
  0.5612545  -0.02747347 -2.49208788  0.1992881  -0.4970017  -1.17475738
 -0.68522354 -2.32770089 -1.82765734]


In [12]:
# 파일 저장, 불러오기(np.save, np.load)
np.save('n1.npy',n)
m1 = np.load('n1.npy')
print(m1)

[[ 0.64964899  0.83399456  0.37257043  0.06854129 -0.36378131]
 [ 1.10935929  0.5612545  -0.02747347 -2.49208788  0.1992881 ]
 [-0.4970017  -1.17475738 -0.68522354 -2.32770089 -1.82765734]]
