# 파일 입출력

In [5]:
import numpy as np

### 파일 처리
- ndarray의 정보를 파일로 저장할 수 있다
- 일반적인 파일 확장자는 npy를 사용한다

In [6]:
# 파일 저장
n = np.random.randn(3,5)
print(n)
n.tofile('n.npy')

[[ 0.30322862 -1.04360132 -0.22526693  0.058809   -0.80200449]
 [-0.6375197  -2.06025825  1.37816865 -1.47746032 -0.7475615 ]
 [ 0.10744119 -0.69285122  0.72693669  0.32094776  0.32945651]]


In [7]:
# 파일 불러오기
m = np.fromfile('n.npy')
print(m)

[ 0.30322862 -1.04360132 -0.22526693  0.058809   -0.80200449 -0.6375197
 -2.06025825  1.37816865 -1.47746032 -0.7475615   0.10744119 -0.69285122
  0.72693669  0.32094776  0.32945651]


In [8]:
m2 = np.fromfile('C:/STUDY/StudyPython22/n.npy')
print(m2)

[ 0.30322862 -1.04360132 -0.22526693  0.058809   -0.80200449 -0.6375197
 -2.06025825  1.37816865 -1.47746032 -0.7475615   0.10744119 -0.69285122
  0.72693669  0.32094776  0.32945651]


In [9]:
# 파일 저장, 불러오기(np.save, np.load)
np.save('n1.npy',n)
m1 = np.load('n1.npy')
print(m1)

[[ 0.30322862 -1.04360132 -0.22526693  0.058809   -0.80200449]
 [-0.6375197  -2.06025825  1.37816865 -1.47746032 -0.7475615 ]
 [ 0.10744119 -0.69285122  0.72693669  0.32094776  0.32945651]]


In [12]:
# txt 파일 저장(np.savetxt)
np.savetxt('n.txt',n)  # 저장할 파일 n

In [18]:
# txt 파일 불러오기
np.loadtxt('n.txt')


array([[ 0.30322862, -1.04360132, -0.22526693,  0.058809  , -0.80200449],
       [-0.6375197 , -2.06025825,  1.37816865, -1.47746032, -0.7475615 ],
       [ 0.10744119, -0.69285122,  0.72693669,  0.32094776,  0.32945651]])

In [29]:
# csv 파일 저장
np.savetxt('n.csv',n)
# np.savetxt('n.csv',n,delimiter=',') 구분자 지정

In [31]:
# csv 파일 불러오기
np.loadtxt('n.csv')  # 파일 저장 문장에 delimiter= 있으면 로드 안됨
#np.loadtxt('n.csv',delimiter=',')  # 파일 저장 문장에 delimiter= 있으면 불러오는 문장에도 deli- 적어야 함.
# dtype=원하는 자료형

array([[ 0.30322862, -1.04360132, -0.22526693,  0.058809  , -0.80200449],
       [-0.6375197 , -2.06025825,  1.37816865, -1.47746032, -0.7475615 ],
       [ 0.10744119, -0.69285122,  0.72693669,  0.32094776,  0.32945651]])

### 파일입출력 연습문제

In [68]:
# 문제1
# 1~25 5x5 2차원 행렬로
arr = np.arange(1,26,dtype=np.int8).reshape(5,5)
print(arr)
np.savetxt('data.csv',arr,delimiter=',')

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [70]:
np.loadtxt('data.csv',delimiter=',',dtype=int)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [ ]:
arr = np.savetxt('data.csv',np.arange(1,26,dtype=int8).reshape(5,5),delimiter=',')

In [65]:
# 문제2
arr1 = np.loadtxt('C:/STUDY/StudyPython22/data/06_data1.txt',dtype=np.str_ #dtype=str)
print(arr1)

[['1' '15' '14' '4']
 ['12' '6' '7' '9']
 ['8' '10' '11' '5']
 ['13' '3' '2' '16']]


In [66]:
np.loadtxt('C:/STUDY/StudyPython22/data/06_data1.txt',delimiter='\t',dtype=np.str_) # delimiter='\t' = 공백이 탭일 때

array([['1', '15', '14', '4'],
       ['12', '6', '7', '9'],
       ['8', '10', '11', '5'],
       ['13', '3', '2', '16']], dtype='<U2')

In [67]:
# 문제3
arr2 = np.loadtxt('C:/STUDY/StudyPython22/data/06_data2.txt',delimiter=',',dtype=np.int8)
# 기존 파일 구분자가 ','라서 delimiter=',' 사용해야함
print(arr2)

[[ 1 15 14  4]
 [12  6  7  9]
 [ 8 10 11  5]
 [13  3  2 16]]


#### 파일처리 문제
- 파일 읽어오기

In [73]:
data = np.loadtxt('C:/STUDY/StudyPython22/data/ex1_지역별전기요금.csv',delimiter=',', dtype=int)
print(data[:5,:])  #상위 5개 데이터

[[      1  565082     273   27177]
 [      2 2827233     444   45111]
 [      3 1144913     289   29043]
 [      4 1131034     230   22436]
 [      5  380425     391   38020]]


- 데이터 모양 확인
- 중복 지역 확인

In [75]:
# 데이터 모양 확인
print(data.shape)

# 중복 지역 확인
print(np.unique(data[:,0]))

(17, 4)
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17]


- 데이터 크기순 정렬(argsort)
- fancy index

In [84]:
# 데이터 크기순 정렬(argsort)
print(data[:,1].argsort())  # print(data[:,1].argsort())[::-1] 결과값 거꾸로 출력

#fancy index
print(data[data[:,1].argsort()])

[ 9 14 10  4  6  0 16 13  5 12 11 15  7  3  2  8  1]
[[     10   49394     580   57091]
 [     15  258605     221   22180]
 [     11  323151     353   35470]
 [      5  380425     391   38020]
 [      7  425659     344   32331]
 [      1  565082     273   27177]
 [     17  584500     268   26899]
 [     14  634696     285   28556]
 [      6  668623     364   35245]
 [     13  726699     249   25120]
 [     12  734723     398   40049]
 [     16  742285     282   27901]
 [      8  947300     366   36274]
 [      4 1131034     230   22436]
 [      3 1144913     289   29043]
 [      9 2737725     361   36569]
 [      2 2827233     444   45111]]


- 데이터 통계

In [87]:
# 데이터 통계
# 전국 대상 가구수의 합
print(np.sum(data[:,1]))
data[:,1].sum()

14882047


14882047

In [89]:
# 가구당 평균 전력 사용량의 전국 평균값
print(round(data[:,2].mean())) 
np.mean(data[:,2])  # data[:,2].mean()

335


335.1764705882353

In [101]:
# 무식하게(?) 평균구하기
e_sum = np.sum(data[:,2])
e_sum

n_rows = data.shape[0]
n_rows

print('가구당 평균 전력 사용량 전국 평균값 : ',round(e_sum / n_rows,2))

가구당 평균 전력 사용량 전국 평균값 :  335.18


In [104]:
# 가구당 평균 전력 사용량이 평균 이상인 지역과 대상 가구수 추출
avg_ = data[:,2].mean() # 가구당 평균 전력 사용량 전국 평균
print(data[data[:,2] > avg_, 0:2])  #2번째 열에서 avg_보다 큰 열 뽑기.

[[      2 2827233]
 [      5  380425]
 [      6  668623]
 [      7  425659]
 [      8  947300]
 [      9 2737725]
 [     10   49394]
 [     11  323151]
 [     12  734723]]


### 파일처리 연습문제

#### 문제1) 위 파일을 읽어보고 상위 3개의 (발생년도, 발생건수, 구성비)의 데이터를 추출해 봅시다.

In [202]:
data1 = np.loadtxt('C:/STUDY/StudyPython22/data/ex2_전년대비_시도별_교통사망사고.csv',delimiter=',', dtype=float)
print(data1[:3,[0,2,3]])

[[2014.   218.     4.8]
 [2014.   872.    19. ]
 [2014.   401.     8.7]]


#### 문제2) 위 데이터에서 부산에서 발생한 교통사망사고 모든 현황을 추출해 봅시다.

In [203]:
print(data1[7,1:6])

#다른 방법(부산의 위치를 알고있을때)
print(data1[7])
#다른 방법
print(data1[data1[:,1] == 8])

[  8.  163.    3.6 -47.  -22.4]
[2014.     8.   163.     3.6  -47.   -22.4]
[[2014.     8.   163.     3.6  -47.   -22.4]]


#### 문제3) 위 데이터에서 전국 사고 발생건수의 합계와 전국 평균을 계산해 봅시다.

In [204]:
print(np.sum(data1[:,2]))
print('전국 사고 발생건수의 총합 : ', data1[:,2].sum())

4583.0
전국 사고 발생건수의 총합 :  4583.0


In [205]:
#외전 평균구하기
print('전국 사고 발생건수의 평균 : ', round(data1[:,2].mean(),3))

전국 사고 발생건수의 평균 :  269.588


#### 문제4) 위 데이터에서 교통사고 증감수가 가장 큰 지역의 모든 현황을 추출해 봅시다.

In [206]:
max_ =  data1[:,4].max() # max(data1[:,4])

print(data1[data1[:,4] == max_, 0:6]) # print(data1[data1[:,4] == max_(data1[:,4])])

[[2014.     6.   182.     4.    19.    11.7]]


In [208]:
np.argmax(data1[:,4])

print(data1[np.argmax(data1[:,4])])

[2014.     6.   182.     4.    19.    11.7]


#### 문제5) 위 데이터에서 교통사고 증감률이 가장 작은 지역의 모든 현황을 추출해 봅시다.

In [207]:
min_ =  data1[:,5].min()

print(data1[data1[:,5] == min_, 0:6])

[[2014.     8.   163.     3.6  -47.   -22.4]]


#### 문제6) 위 데이터에서 사고 발생 건수가 400건 이상인 곳의 지역과 교통사고 발생건수, 증감수, 증감률을 추출해 봅시다.

In [189]:
a= data1[data1[:,2] >= 400,]
print(a[:,[1,2,4,5]])

print(data1[data1[:,2] >= 400][:,[1,2,4,5]]) #인덱싱 따로 진행

[[  2 872 -45  -4]
 [  3 401 -45 -10]
 [  4 464 -41  -8]
 [ 13 400 -35  -8]]
[[  2 872 -45  -4]
 [  3 401 -45 -10]
 [  4 464 -41  -8]
 [ 13 400 -35  -8]]
